# Linear Algebra Assignment

# [1] Checking various properties (such as symmetry, idempotency, singularity,orthogonality, definiteness etc) of the given matrix


In [1]:
import numpy as np

In [16]:
A=np.random.randint(1,8,(3,3))
print(A)

[[1 4 4]
 [6 2 6]
 [1 6 6]]


In [17]:
def Properties(A):
    row,col=A.shape
    print("The given Matrix is \n",A)
    print("The Determinant Of the Matrix is",round(np.linalg.det(A)))
    print("The Rank of the Matrix is: ",np.linalg.matrix_rank(A ))
    if row==col:
        print("The given Matrix is Square Matrix")
    else:
        print("The given Matrix is Not Square Matrix")
    
    if (A.T==A).all():
        print("The given Matrix is Symmetric Matrix")
    else:
        print("The given Matrix is Not Symmetric Matrix")
    if (np.linalg.det(A)!=0).all():
        print("The given Matrix is Not Singular Matrix")
    else:
        print("The given Matrix is Non Singular Matrix")
    if (np.linalg.inv(A)==A.T).all():
        print("The given Matrix is Orthogonal Matrix")
    else:
        print("The given Matrix is Not Orthogonal Matrix")
    if (A@A==A).all():
        print("The given Matrix is Idempotent Matrix")
    else:
        print("The given Matrix is Not Idempotent Matrix")
        

The given Matrix is 
 [[1 4 4]
 [6 2 6]
 [1 6 6]]
The Determinant Of the Matrix is -8
The Rank of the Matrix is:  3
The given Matrix is Square Matrix
The given Matrix is Not Symmetric Matrix
The given Matrix is Not Singular Matrix
The given Matrix is Not Orthogonal Matrix
The given Matrix is Not Idempotent Matrix


   # 2] Cramer's Rule


# 1. Solve the following systems of linear equations using Cramer’s rule.
(a) 2x1 − x2 + x3 = −3,x1 + x2 −3x3 = 17, 5x1 −2x2 −4x3 = 20

(b) 2x1 +3x2 − x3 = 4,x1 +4x2 + x3 = −1, 5x1 − x2 +2x3 = 1

(c) −x1 +2x2 +4x3 −2x4 +3x5 = 24, 20x1 +5x2 +3x3 −2x4 − x5 = 29,2x1 +18x2 +60x3 +5x4 −3x5 = 177, 2x1 +4x2 +4x3 +3x5 = 26

(d) 2x1 +3x2 − x3 = 4, x1 +4x2 + x3 = −1, 5x1 − x2 +2x3 = 1, 2x1 +3x2−6x3 +5x4 +4x5 = 0

In [8]:
import numpy as np

In [10]:
def Cramer(A,b):
    import numpy as np
    d=np.linalg.det(A)
    if(d!=0):
        row,col=A.shape
        x=[]
        for i in range(col):  
            C=A.copy()
            C[:,i]=b
            v=np.linalg.det(C)/np.linalg.det(A)
            x.append(round(v))
        print("The solution of the S.O.E. is:")
        print(x)
    else:
        print("The System has no solution")

In [11]:

A=np.matrix("2,-1,1;1,1,-3;5,-2,-4")
b=np.matrix("-3,17,20").transpose()
Cramer(A,b)

The solution of the S.O.E. is:
[2, 3, -4]


In [12]:
A=np.matrix("2,3,-1;1,4,1;5,-1,2")
b=np.matrix("4,-1,1").transpose()
Cramer(A,b)

The solution of the S.O.E. is:
[1, 0, -2]


In [13]:
A=np.matrix("-1,2,4,-2,3;20,5,3,-2,-1;2,18,60,5,-3;2,4,4,0,3;2,3,-6,5,4")
b=np.matrix("24,29,177,26,0").transpose()
Cramer(A,b)

The solution of the S.O.E. is:
[2, -3, 4, 1, 6]


#  3] g-Inverse of the Non Full Rank Matrix

In [19]:
import numpy as np


In [20]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
A=np.matrix("1,2,3;4,5,6;7,8,9")

In [27]:
r=np.linalg.matrix_rank(A)
print("Rank of the matrix is: ",r)
m,n=A.shape
G=np.zeros((m,n))
B=A[np.ix_([0,r],[0,r])]
r1=np.linalg.matrix_rank(B)
if(r==r1):
    G[np.ix_([0,r],[0,r])]=np.linalg.inv(B).T
    G=G.T
print("The g-Inverse of the Matrix is:\n" ,np.round(G))

Rank of the matrix is:  2
The g-Inverse of the Matrix is:
 [[-1.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  0. -0.]]


In [28]:
#Verify the properties
#trace(AG)=trace(GA)=rank(A)
if np.trace(A@G)==round(np.trace(G@A))==np.linalg.matrix_rank(A):
    print("Property Satisfied")
else:
    print("Property not Satisfied")

Property not Satisfied


# 4]  Solution Of Systems Of Linear Equations

In [75]:
import numpy as np

In [70]:
A=np.matrix("2,3,-1;1,4,1;5,-1,2")
A1=np.matrix("1,2,3;4,5,6;7,8,9")
b=np.matrix("4,-1,1").transpose()
print(round(np.linalg.det(A1)))
print(round(np.linalg.det(A)))

0
48


In [77]:
def SLE(A,b):
    if round(np.linalg.det(A))==0:
        r=np.linalg.matrix_rank(A)
        print("Rank of the matrix is: ",r)
        m,n=A.shape
        G=np.zeros((m,n))
        B=A[np.ix_([0,r],[0,r])]
        r1=np.linalg.matrix_rank(B)
        if(r==r1):
            G[np.ix_([0,r],[0,r])]=np.linalg.inv(B).T
            G=G.T
        print("The g-Inverse of the Matrix is:\n" ,G)
        print("\nThe System has Infinite solutions")
        z1=np.random.rand(n,1)*10
        z2=np.random.rand(n,1)*10
        I=np.eye(n)
        print("first solution of SLE:\n",np.round(G*b+(I-G*A)*z1))
        print("Second solution of SLE:\n",np.round(G*b+(I-G*A)*z2))
    else:
        Inv=np.linalg.inv(A)
        #AX=b
        #X=inv(A)*b
        s=np.linalg.inv(A)*b
        print("The unique solution of  SLE is\n:",np.round(s))
        

In [78]:
SLE(A,b)

The unique solution of  SLE is
: [[ 1.]
 [ 0.]
 [-2.]]


In [79]:
SLE(A1,b)


Rank of the matrix is:  2
The g-Inverse of the Matrix is:
 [[-0.75        0.          0.25      ]
 [ 0.          0.          0.        ]
 [ 0.58333333  0.         -0.08333333]]

The System has Infinite solutions
first solution of SLE:
 [[-5.]
 [ 5.]
 [-0.]]
Second solution of SLE:
 [[-4.]
 [ 2.]
 [ 1.]]


# 5] Using Spectral Decomposition Find the Power of the matrix

In [59]:
import numpy as np

In [60]:
A=np.array([[4,1,3,1],[1,4,1,3],[3,1,4,1],[1,3,1,4]])

In [61]:
P,L=np.linalg.eig(A)

In [62]:
E=np.diagflat(np.linalg.eigvals(A))
print(E)

[[9. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 1.]]


In [63]:
def SDT_Power(A,c):
    import numpy as np
    P,L=np.linalg.eig(A)
    E=np.diag(list(np.linalg.eigvals(A)))
    return np.round(L@E**c@L.T)

In [64]:
SDT_Power(A,2) #A^2

array([[27., 14., 26., 14.],
       [14., 27., 14., 26.],
       [26., 14., 27., 14.],
       [14., 26., 14., 27.]])

In [65]:
SDT_Power(A,7) #A^7

array([[1215274., 1176211., 1215273., 1176211.],
       [1176211., 1215274., 1176211., 1215273.],
       [1215273., 1176211., 1215274., 1176211.],
       [1176211., 1215273., 1176211., 1215274.]])

In [66]:
SDT_Power(A,1/2) #A^0.5

array([[2., 0., 1., 0.],
       [0., 2., 0., 1.],
       [1., 0., 2., 0.],
       [0., 1., 0., 2.]])

In [67]:
SDT_Power(A,3/2) #A^1.5

array([[10.,  4.,  9.,  4.],
       [ 4., 10.,  4.,  9.],
       [ 9.,  4., 10.,  4.],
       [ 4.,  9.,  4., 10.]])

# 6] GSO(Gram_Smith_Orthogonalization)

In [11]:
import numpy as np

In [12]:
x1=np.array([3,1,-1,3])
x2=np.array([-5,1,5,-7])
x3=np.array([1,1,-2,8])

In [13]:
def GSO3(x1,x2,x3):
    import pandas as pd
    import numpy as np
    z1=x1
    z2=x2-(np.inner(x2,z1)/np.inner(z1,z1)*z1)
    z3=x3-(np.inner(x3,z1)/np.inner(z1,z1)*z1)-(np.inner(x3,z2)/np.inner(z2,z2)*z2)
    
    print("Orthogonal:\n",z1,z2,z3,"\nOrthonormal\n:",z1/np.linalg.norm(z1),z2/np.linalg.norm(z2),z3/np.linalg.norm(z3))
    

In [14]:
GSO3 (x1,x2,x3)

Orthogonal:
 [ 3  1 -1  3] [ 1.  3.  3. -1.] [-3.  1.  1.  3.] 
Orthonormal
: [ 0.67082039  0.2236068  -0.2236068   0.67082039] [ 0.2236068   0.67082039  0.67082039 -0.2236068 ] [-0.67082039  0.2236068   0.2236068   0.67082039]


In [36]:
np.random.seed(1)
x=np.random.randint(0,2,(4,4))
print(x)

[[1 1 0 0]
 [1 1 1 1]
 [1 0 0 1]
 [0 1 1 0]]


In [44]:
x1=x[:,0]
x2=x[:,1]
x3=x[:,2]
x4=x[:,3]

In [45]:
def GSO4(x1,x2,x3,x4):
    import pandas as pd
    import numpy as np
    z1=x1
    z2=x2-(np.inner(x2,z1)/np.inner(z1,z1)*z1)
    z3=x3-(np.inner(x3,z1)/np.inner(z1,z1)*z1)-(np.inner(x3,z2)/np.inner(z2,z2)*z2)
    z4=x4-(np.inner(x4,z1)/np.inner(z1,z1)*z1)-(np.inner(x4,z2)/np.inner(z2,z2)*z2)-(np.inner(x4,z3)/np.inner(z3,z3)*z3)
    l=[np.round(z1),np.round(z2),np.round(z3),np.round(z4)]
    l1=[z1/np.linalg.norm(z1),z2/np.linalg.norm(z2),z3/np.linalg.norm(z3),z4/np.linalg.norm(z4)]
    l2=[]
    for i in l1:
        l2.append(np.round(i))
    print("Orthogonal: \n",l,"\nOrthonormal: \n",l2)

In [46]:
GSO4(x1,x2,x3,x4)

Orthogonal: 
 [array([1, 1, 1, 0]), array([ 0.,  0., -1.,  1.]), array([-1.,  0.,  0.,  0.]), array([ 0., -0., -0.,  0.])] 
Orthonormal: 
 [array([1., 1., 1., 0.]), array([ 0.,  0., -1.,  1.]), array([-1.,  1.,  0.,  0.]), array([ 1., -0., -0.,  0.])]
